export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const CLEAR_TASK_LIST = 'CLEAR_TASK_LIST';
export const ADD_TASK_IN_HISTORY = 'ADD_TASK_IN_HISTORY';
export const REMOVE_TASK_FROM_HISTORY = 'REMOVE_TASK_FROM_HISTORY';
export const CLEAR_TASK_HISTORY = 'CLEAR_TASK_HISTORY';